/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import clases.Imprimir;
import clases.Render;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manuel
 */
public class GestionarReportes extends javax.swing.JFrame {

    String user;
    int alumno_id = 0;
    String[] user2;
    DefaultTableModel model = new DefaultTableModel() {  //Acceso a los métodos necesarios para modificar una tabla
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form GestionarAdministradores
     */
    public GestionarReportes() {
        initComponents();
        user = Administrador.nombre_usuario;
        user2 = user.split(" ");
        setTitle("Gestionar Reportes de Inscripción - Sesión de " + user2[0]);

        setSize(970, 360);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        //Clase ImageIcon que permite asignar una imagen a un jLabel con la ruta en: ("")
        ImageIcon fondo = new ImageIcon("src/images/fondo unexac.jpg");
        //Clase Icon para reescalar la imagen a las coordenadas de la interfaz
        Icon icono_fondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(), jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        //Se le asigna la imagen de fondo al jLabel_fondo
        jLabel_fondo.setIcon(icono_fondo);
        //Instruccion necesaria para aplicar los cambios
        this.repaint();

        Tabla(jTable_reportes);

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/iconounex.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_reportes = new javax.swing.JTable();
        jButton_refrescar = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestionar Reportes de Inscripción");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jTable_reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_reportes.setRowHeight(40);
        jScrollPane1.setViewportView(jTable_reportes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 965, 180));

        jButton_refrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar-Icon made by Freepik Icons from www.flaticon.com.png"))); // NOI18N
        jButton_refrescar.setBorder(null);
        jButton_refrescar.setContentAreaFilled(false);
        jButton_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refrescarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_refrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 40, 32));

        jLabel_footer.setText("Creado por Manuel Torrealba y Stefany Villamizar");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refrescarActionPerformed
        dispose();
        GestionarReportes gestionalum = new GestionarReportes();
        gestionalum.setVisible(true);
    }//GEN-LAST:event_jButton_refrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_refrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_reportes;
    // End of variables declaration//GEN-END:variables

    private void Tabla(JTable tabla) {
        tabla.setDefaultRenderer(Object.class, new Render());
        JButton jButton_imprimir_reporte = new JButton("PDF");
        //Clase ImageIcon que permite asignar una imagen a un jButton con la ruta en: ("")
        ImageIcon pdf = new ImageIcon("src/images/pdfdescargar2-Icon Icons from www.icon-icons.com.png");
        //Se le asigna la imagen de fondo al jLabel_fondo
        jButton_imprimir_reporte.setIcon(pdf);
        jButton_imprimir_reporte.setBorder(null);
        jButton_imprimir_reporte.setName("imprimir");

        model.addColumn(" ");
        model.addColumn("Nombres");
        model.addColumn("Apellidos");
        model.addColumn("Cédula");
        model.addColumn("Expediente");
        model.addColumn("Especialidad");
        model.addColumn("Correo Electrónico");
        model.addColumn("Estatus");
        model.addColumn("Registrado por");
        model.addColumn("Descargar");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT id, nombres, apellidos, cedula, expediente, especialidad, email, estatus, registrado_por FROM alumnos");

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[10];

                for (int i = 0; i < 9; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                fila[9] = jButton_imprimir_reporte;
                model.addRow(fila);
            }

            jTable_reportes.setModel(model);

            cn.close();

        } catch (SQLException e) {
            System.err.println("Error al llenar tabla " + e);
            JOptionPane.showMessageDialog(null, "Error al mostrar la informacion. Contacte con un administrador");
        }

        tabla.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = tabla.rowAtPoint(e.getPoint());
                int columna_point = tabla.columnAtPoint(e.getPoint());

                if (fila_point >= 0 && columna_point >= 0) {
                    Object value = jTable_reportes.getValueAt(fila_point, columna_point);
                    if (value instanceof JButton) {
                        ((JButton) value).doClick();
                        JButton boton = (JButton) value;

                        if (boton.getName().equals("imprimir")) {
                            alumno_id = ((Number) jTable_reportes.getValueAt(fila_point, 0)).intValue();
                            Imprimir imprimir = new Imprimir();
                            imprimir.ImprimirReporteDeInscripcion(alumno_id);
                        }
                    }
                }
            }

        });

    }
}
