/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Validador;
import clases.EncriptarPassword;
import clases.Conexion;
import java.awt.Color;
import java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Manuel
 */
public class InformacionAdministradores extends javax.swing.JFrame {

    String user, user_update;
    int ID_update;
    String[] user2, user3;

    /**
     * Creates new form RegistrarAdministradores
     */
    public InformacionAdministradores() {
        initComponents();
        user = Administrador.nombre_usuario;
        user2 = user.split(" ");
        user_update = GestionarAdministradores.user_update;
        user3 = user_update.split(" ");
        ID_update = GestionarAdministradores.ID_update;
        
        setTitle("Información del administrador(a): " + user3[0] +" - Sesión de " + user2[0]);
        jLabel_Titulo.setText("Información del administrador(a): "+user3[0]);

        setSize(580, 490);
        setResizable(false);
        setLocationRelativeTo(null);

        //Evita que se cierre todo el programa cuando esta ventana se cierre
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        //Clase ImageIcon que permite asignar una imagen a un jLabel con la ruta en: ("")
        ImageIcon fondo = new ImageIcon("src/images/fondo unexac.jpg");
        //Clase Icon para reescalar la imagen a las coordenadas de la interfaz
        Icon icono_fondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(), jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        //Se le asigna la imagen de fondo al jLabel_fondo
        jLabel_fondo.setIcon(icono_fondo);
        //Instruccion necesaria para aplicar los cambios
        this.repaint();
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select nombre, apellido, cedula, email, estatus, registrado_por from administradores where id = "+ID_update);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                txt_nombre.setText(rs.getString("nombre"));
                txt_apellido.setText(rs.getString("apellido"));
                txt_email.setText(rs.getString("email"));
                txt_cedula.setText(rs.getString("cedula"));
                if(rs.getString("estatus").equals("Activo")){
                    cmb_estatus.setSelectedIndex(0);
                }else{
                    cmb_estatus.setSelectedIndex(1);
                }
                txt_registrado_por.setText(rs.getString("registrado_por"));
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Ha ocurrido un error al consultar el administrador. Contacte con un administrador "+e);
            JOptionPane.showMessageDialog(null, "Ha acurrido un error al consultar");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/iconounex.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_estatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_registrado_por = new javax.swing.JTextField();
        jLabel_footer = new javax.swing.JLabel();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Password = new javax.swing.JButton();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Información del administrador: ");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombres:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(5, 125, 203));
        txt_nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Apellidos:");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txt_apellido.setBackground(new java.awt.Color(5, 125, 203));
        txt_apellido.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_apellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Correo electrónico:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txt_email.setBackground(new java.awt.Color(5, 125, 203));
        txt_email.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cédula:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        txt_cedula.setBackground(new java.awt.Color(5, 125, 203));
        txt_cedula.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_cedula.setForeground(new java.awt.Color(255, 255, 255));
        txt_cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 150, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Estatus:");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        cmb_estatus.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cmb_estatus.setForeground(new java.awt.Color(255, 255, 255));
        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmb_estatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 150, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registrado por:");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        txt_registrado_por.setEditable(false);
        txt_registrado_por.setBackground(new java.awt.Color(5, 125, 203));
        txt_registrado_por.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_registrado_por.setForeground(new java.awt.Color(255, 255, 255));
        txt_registrado_por.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_registrado_por.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_registrado_por, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 170, -1));

        jLabel_footer.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_footer.setText("Creado por Manuel Torrealba y Stefany Villamizar");
        jLabel_footer.setToolTipText("");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        jButton_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizaradministradores-Icon made by Freepik Icons from www.flaticon.com.png"))); // NOI18N
        jButton_Actualizar.setBorder(null);
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 90, 80));

        jButton_Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizarcontraseña-Icon made by Freepik Icons from www.flaticon.com.png"))); // NOI18N
        jButton_Password.setBorder(null);
        jButton_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 90, 80));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
        int estatusInt;
        int validacion = 0;
        String nombre, apellido, cedula, email, estatusString = "";

        nombre = txt_nombre.getText().trim();
        apellido = txt_apellido.getText().trim();
        cedula = txt_cedula.getText().trim();
        email = txt_email.getText().trim();
        estatusInt = cmb_estatus.getSelectedIndex() + 1;

        //Validacion NOMBRE
        if (nombre.equals("")) {
            txt_nombre.setBackground(Color.red);
            validacion++;
        } else {
            Validador validar = new Validador(nombre);
            validar.ValidarNombre();
            if (validar.verificado == true) {
                txt_nombre.setBackground(new Color(5, 125, 203));
            } else {
                validacion++;
                JOptionPane.showMessageDialog(null, "No");
            }
        }

        //Validacion APELLIDO
        if (apellido.equals("")) {
            txt_apellido.setBackground(Color.red);
            validacion++;
        } else {
            Validador validar = new Validador(apellido);
            validar.ValidarNombre();
            if (validar.verificado == true) {
                txt_apellido.setBackground(new Color(5, 125, 203));
            } else {
                validacion++;
                JOptionPane.showMessageDialog(null, "No");
            }
        }

        //Validacion EMAIL
        if (email.equals("")) {
            txt_email.setBackground(Color.red);
            validacion++;
        } else if (email.contains(" ")) {
            txt_email.setBackground(Color.red);
            validacion++;
        } else {
            Validador validar = new Validador(email);
            validar.ValidarEmail();
            if (validar.verificado == true) {
                txt_email.setBackground(new Color(5, 125, 203));
            } else {
                validacion++;
                JOptionPane.showMessageDialog(null, "No");
            }
        }

        //Validacion CEDULA
        if (cedula.equals("")) {
            txt_cedula.setBackground(Color.red);
            validacion++;
        } else if (cedula.contains(" ")) {
            txt_cedula.setBackground(Color.red);
            validacion++;
        } else {
            Validador validar = new Validador(cedula);
            validar.ValidarCedula();
            if (validar.verificado == true) {
                txt_cedula.setBackground(new Color(5, 125, 203));
            } else {
                validacion++;
                JOptionPane.showMessageDialog(null, "No");
            }
        }

        //Validacion ESTATUS
        if (estatusInt == 1) {
            estatusString = "Activo";
        } else if (estatusInt == 2) {
            estatusString = "Inactivo";
        }

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select cedula from administradores where cedula = '" + cedula + "' and not id = "+ID_update);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_cedula.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "El número de cedula ya pertenece a un administrador");
                cn.close();
            } else {
                cn.close();

                if (validacion == 0) {
                    try {

                        Connection cn2 = Conexion.conectar();
                        PreparedStatement pst2 = cn2.prepareStatement(
                                "update administradores set nombre=?, apellido=?, cedula=?, email=?, estatus=? where id = "+ID_update);pst2.setInt(1, 0); //Columna ID
                        pst2.setString(1, nombre);
                        pst2.setString(2, apellido);
                        pst2.setString(3, cedula);
                        pst2.setString(4, email);
                        pst2.setString(5, estatusString);

                        pst2.executeUpdate();
                        cn2.close();

                        Limpiar();
                        Verificado();

                        JOptionPane.showMessageDialog(null, "La actualización del administrador(a) fue realizada correctamente");
                        this.dispose(); //Sirve para liberar recursos cerrando la pestaña de vista

                    } catch (Exception e) {
                        System.err.println("Error al actualizar administrador " + e);
                        JOptionPane.showMessageDialog(null, "!ERROR al actualizar administrador!, contacte con un administrador.!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos");
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al validar la cedula del administrador" + e);
            JOptionPane.showMessageDialog(null, "Error al comparar cédula, por favor contacte con un administrador");
        }
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PasswordActionPerformed
        ModificarPassword modificarpassword = new ModificarPassword();
        modificarpassword.setVisible(true);
    }//GEN-LAST:event_jButton_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionAdministradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Password;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_registrado_por;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_cedula.setText("");
        txt_email.setText("");
        cmb_estatus.setSelectedIndex(0);
    }

    private void Verificado() {
        txt_nombre.setBackground(Color.green);
        txt_apellido.setBackground(Color.green);
        txt_cedula.setBackground(Color.green);
        txt_email.setBackground(Color.green);
    }
}
