/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

//Libreria para la clase Icon que permite
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
//Libreria para la clase ImageIcon que permite 
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel
 */
public class Login extends javax.swing.JFrame {

    //variable para enviar datos entre interfaces
    public static String user = "";
    String pass = "";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //Metodo para asignar el tamaño a la interfaz
        setSize(400, 550);
        //Metodo para evitar que el usuario cambie el tamaño de la interfaz
        setResizable(false);
        //Metodo para asignarle el titulo a la interfaz
        setTitle("Acceso al sistema de la UNEXPO LCM");
        //Metodo para que la interfaz aparazca en el centro de la pantalla
        setLocationRelativeTo(null);

        //Clase ImageIcon que permite asignar una imagen a un jLabel con la ruta en: ("")
        ImageIcon fondo = new ImageIcon("src/images/FondoPrincipal.jpg");
        //Clase Icon para reescalar la imagen a las coordenadas de la interfaz
        Icon icono_fondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(), jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        //Se le asigna la imagen de fondo al jLabel_fondo
        jLabel_fondo.setIcon(icono_fondo);
        //Instruccion necesaria para aplicar los cambios
        this.repaint();

        ImageIcon logo = new ImageIcon("src/images/logounex.png");
        Icon icono_logo = new ImageIcon(logo.getImage().getScaledInstance(jLabel_logo.getWidth(), jLabel_logo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_logo.setIcon(icono_logo);
        this.repaint();
    }

    //Sobrescribimos el metodo Image para cambiar el icono a la interfaz
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/iconounex.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_logo = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jButton_acceder = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 290, 270));

        txt_usuario.setBackground(new java.awt.Color(5, 125, 203));
        txt_usuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_usuario.setToolTipText("Ingrese su correo electrónico");
        txt_usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_usuario.setName(""); // NOI18N
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 330, 210, -1));
        txt_usuario.getAccessibleContext().setAccessibleName("");

        txt_password.setBackground(new java.awt.Color(5, 125, 203));
        txt_password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setToolTipText("Introduzca su contraseña");
        txt_password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 370, 210, -1));

        jButton_acceder.setBackground(new java.awt.Color(5, 125, 203));
        jButton_acceder.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_acceder.setForeground(new java.awt.Color(255, 255, 255));
        jButton_acceder.setText("ACCEDER");
        jButton_acceder.setToolTipText("");
        jButton_acceder.setAutoscrolls(true);
        jButton_acceder.setBorder(null);
        jButton_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_accederActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 420, 210, 35));
        jButton_acceder.getAccessibleContext().setAccessibleName("");

        jLabel_footer.setText("Creado por Manuel Torrealba y Stefany Villamizar");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void jButton_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_accederActionPerformed

        user = txt_usuario.getText().trim();
        pass = txt_password.getText().trim();

        if (!user.equals("") && !pass.equals("")) {

            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select estatus from administradores where email = '" + user
                        + "' and password = '" + pass + "'");

                ResultSet rs = pst.executeQuery();

                PreparedStatement pst2 = cn.prepareStatement(
                        "select estatus from alumnos where email = '" + user
                        + "' and password = '" + pass + "'");

                ResultSet rs2 = pst2.executeQuery();

                if (rs.next()) {

                    String estatus = rs.getString("estatus");

                    if (estatus.equalsIgnoreCase("Activo")) {
                        //Metodo para cerrar la interfaz de Login
                        dispose();
                        new Administrador().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Actualmente se encuentra inactivo, por favor comuniquese con un administrador.");
                        txt_usuario.setText("");
                        txt_password.setText("");
                    }

                } else if (rs2.next()) {
                    String estatus = rs2.getString("estatus");

                    if (estatus.equalsIgnoreCase("Activo")) {
                        //Metodo para cerrar la interfaz de Login
                        dispose();
                        new Alumno().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Actualmente se encuentra inactivo, por favor comuniquese con un administrador.");
                        txt_usuario.setText("");
                        txt_password.setText("");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "¡Error al iniciar sesion!, contacte con un administrador.");
                    txt_usuario.setText("");
                    txt_password.setText("");
                }

            } catch (SQLException e) {
                System.err.println("Error en el boton Acceder. " + e);
                JOptionPane.showMessageDialog(null, "¡Error al iniciar sesion!, contacte con un administrador.");

            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes ingresar un correo y contraseña");
        }

    }//GEN-LAST:event_jButton_accederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_acceder;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
