/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.EncriptarPassword;
//Libreria para la clase Icon que permite
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
//Libreria para la clase ImageIcon que permite 
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Manuel
 */
public class ModificarPassword extends javax.swing.JFrame {

    String user, user_update;
    int ID_update;
    String[] user2, user3;

    /**
     * Creates new form nuevo
     */
    public ModificarPassword() {
        initComponents();
        user = Login.user;
        user_update = GestionarAdministradores.user_update;
        user2 = user.split(" ");
        user3 = user_update.split(" ");

        //Metodo para asignar el tamaño a la interfaz
        setSize(400, 400);
        //Metodo para evitar que el usuario cambie el tamaño de la interfaz
        setResizable(false);
        //Metodo para asignarle el titulo a la interfaz
        setTitle("Actualizar contraseña - Sesión de " + user2[0]);
        //Metodo para que la interfaz aparazca en el centro de la pantalla
        setLocationRelativeTo(null);

        //Evita que se cierre todo el programa cuando esta ventana se cierre
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        //Clase ImageIcon que permite asignar una imagen a un jLabel con la ruta en: ("")
        ImageIcon fondo = new ImageIcon("src/images/fondo unexac.jpg");
        //Clase Icon para reescalar la imagen a las coordenadas de la interfaz
        Icon icono_fondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(), jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        //Se le asigna la imagen de fondo al jLabel_fondo
        jLabel_fondo.setIcon(icono_fondo);
        //Instruccion necesaria para aplicar los cambios
        this.repaint();
    }

    //Sobrescribimos el metodo Image para cambiar el icono a la interfaz
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/iconounex.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txt_password2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actualizar contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nueva Contraseña:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        txt_password.setBackground(new java.awt.Color(5, 125, 203));
        txt_password.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Repetir Contraseña:");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        txt_password2.setBackground(new java.awt.Color(5, 125, 203));
        txt_password2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_password2.setForeground(new java.awt.Color(255, 255, 255));
        txt_password2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 150, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contraseña-Icon made by Gregor Cresnar from www.flaticon.com (2).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 90, 80));

        jLabel_footer.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_footer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_footer.setText("Creado por Manuel Torrealba y Stefany Villamizar");
        jLabel_footer.setToolTipText("");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 290, 20));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int validacion = 0;
        String password, password2, passwordencode = "", passwordencode2 = "";

        password = txt_password.getText().trim();
        password2 = txt_password2.getText().trim();

        //Validacion Password 1
        if (password.equals("")) {
            txt_password.setBackground(Color.red);
            validacion++;
        } else if (password.contains(" ")) {
            txt_password.setBackground(Color.red);
            validacion++;
        } else {
            EncriptarPassword passwordencriptada = new EncriptarPassword(password);
            passwordencriptada.encode();
            passwordencode = passwordencriptada.encriptacion.trim();
            if (passwordencode.equals("")) {
                validacion++;
            }
            txt_password.setBackground(new Color(5, 125, 203));
        }

        //Validacion Password 2
        if (password2.equals("")) {
            txt_password2.setBackground(Color.red);
            validacion++;
        } else if (password2.contains(" ")) {
            txt_password2.setBackground(Color.red);
            validacion++;
        } else {
            EncriptarPassword passwordencriptada = new EncriptarPassword(password2);
            passwordencriptada.encode();
            passwordencode2 = passwordencriptada.encriptacion.trim();
            if (passwordencode2.equals("")) {
                validacion++;
            }
            txt_password2.setBackground(new Color(5, 125, 203));
        }

        if (validacion == 0) {
            if (passwordencode.equals(passwordencode2)) {
                try {
                    ID_update = GestionarAdministradores.ID_update;
                    Connection cn = Conexion.conectar();
                    PreparedStatement pst = cn.prepareStatement(
                            "update administradores set password = ? where id = " + ID_update);
                    pst.setString(1, passwordencode);

                    pst.executeUpdate();
                    cn.close();
                    Limpiar();
                    Verificado();
                    this.dispose();
                } catch (SQLException e) {
                    System.err.println("Ha ocurrido un error al actualizar la contraseña. Contacte con un administrador " + e);
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error al actualizar la contraseña. Contacte con un administrador");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas deben coincidir");
                txt_password2.setBackground(Color.red);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ModificarPassword().setVisible(true);
            }
        });
    }

    private void Limpiar() {
        txt_password.setText("");
        txt_password2.setText("");
    }

    private void Verificado() {
        JOptionPane.showMessageDialog(null, "La contraseña ha sido actualizada correctamente");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_password2;
    // End of variables declaration//GEN-END:variables
}
