package ventanas;

import clases.Conexion;
import clases.LlenarComboBox;
import clases.LlenarJLabel;
import java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Manuel
 */
public class RegistrarMateriasAlumnos extends javax.swing.JFrame {

    String materia_codigo = "", materia_nombre = "", materia_seccion = "", user, especialidad_update, materia_modificar = "";
    int ID_update;
    String[] user2;

    /**
     * Creates new form RegistrarMateriasAlumnos
     */
    public RegistrarMateriasAlumnos() {
        initComponents();
        materia_codigo = InformacionAlumnos.materia_codigo;
        materia_nombre = InformacionAlumnos.materia_nombre;
        materia_seccion = InformacionAlumnos.materia_seccion;
        user = Administrador.nombre_usuario;
        user2 = user.split(" ");
        ID_update = GestionarAlumnos.ID_update;
        especialidad_update = GestionarAlumnos.especialidad_update;

        setSize(400, 530);
        setResizable(false);
        setLocationRelativeTo(null);

        //Evita que se cierre todo el programa cuando esta ventana se cierre
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        setTitle("Añadir materia - Sesion de " + user2[0]);

        //Clase ImageIcon que permite asignar una imagen a un jLabel con la ruta en: ("")
        ImageIcon fondo = new ImageIcon("src/images/fondo unexac.jpg");
        //Clase Icon para reescalar la imagen a las coordenadas de la interfaz
        Icon icono_fondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(), jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        //Se le asigna la imagen de fondo al jLabel_fondo
        jLabel_fondo.setIcon(icono_fondo);
        //Instruccion necesaria para aplicar los cambios
        this.repaint();

        LlenarComboBox.ComboBoxNombre(cmb_nombre_materia, especialidad_update);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/iconounex.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_nombre_materia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel_codigo_materia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_seccion_materia = new javax.swing.JComboBox<>();
        jButton_Añadir = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Añadir Materia:");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        cmb_nombre_materia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_nombre_materiaItemStateChanged(evt);
            }
        });
        getContentPane().add(cmb_nombre_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 290, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Código:");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel_codigo_materia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_codigo_materia.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_codigo_materia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_codigo_materia.setText("AAAABBBB");
        jLabel_codigo_materia.setDoubleBuffered(true);
        getContentPane().add(jLabel_codigo_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 280, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sección:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        getContentPane().add(cmb_seccion_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 290, 40));

        jButton_Añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregarmateria-Icon Icons from www.icon-icons.com.png"))); // NOI18N
        jButton_Añadir.setBorder(null);
        jButton_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AñadirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 90, 80));

        jLabel_footer.setText("Creado por Manuel Torrealba y Stefany Villamizar");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AñadirActionPerformed
        int validacion = 0;
        String[] materia = InformacionAlumnos.materia;
        String materias_añadir = InformacionAlumnos.materias;
        for (int i = 0; i < materia.length; i++) {
            if (materia[i].contains(cmb_nombre_materia.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(null, "El alumno ya se encuentra en la asignatura introducida");
                validacion++;
            }
        }
        materias_añadir += jLabel_codigo_materia.getText()+","+cmb_nombre_materia.getSelectedItem().toString()+","+cmb_seccion_materia.getSelectedItem()+"-";

        if (validacion == 0) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "UPDATE alumnos set materias_inscritas = ? WHERE id = " + ID_update);
                pst.setString(1, materias_añadir);
                pst.executeUpdate();
                cn.close();

                JOptionPane.showMessageDialog(null, "La asignatura se ha agregado exitosamente");
                InformacionAlumnos infoalum = new InformacionAlumnos();
                infoalum.setVisible(true);
                this.dispose();

            } catch (SQLException e) {
                System.out.println("Ha ocurrio un error al actualizar la seccion " + e);
            }
        }
    }//GEN-LAST:event_jButton_AñadirActionPerformed

    private void cmb_nombre_materiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_nombre_materiaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            cmb_seccion_materia.setModel(new DefaultComboBoxModel(LlenarComboBox.ComboBoxSeccion(cmb_nombre_materia.getSelectedItem().toString())));
            LlenarJLabel.LabelCodigo(jLabel_codigo_materia, cmb_nombre_materia.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmb_nombre_materiaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarMateriasAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarMateriasAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarMateriasAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarMateriasAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarMateriasAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_nombre_materia;
    private javax.swing.JComboBox<String> cmb_seccion_materia;
    private javax.swing.JButton jButton_Añadir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_codigo_materia;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_footer;
    // End of variables declaration//GEN-END:variables
}
