package ventanas;

import clases.Conexion;
import clases.LlenarComboBox;
import clases.LlenarJLabel;
import clases.Validador;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Manuel
 */
public class RegistrarMateriasAdministrador extends javax.swing.JFrame {

    String user;
    int ID_update, actualizar = 0;
    String[] user2;

    /**
     * Creates new form RegistrarMateriasAlumnos
     */
    public RegistrarMateriasAdministrador() {
        initComponents();
        user = Administrador.nombre_usuario;
        user2 = user.split(" ");

        setSize(400, 670);
        setResizable(false);
        setLocationRelativeTo(null);

        //Evita que se cierre todo el programa cuando esta ventana se cierre
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        setTitle("Añadir materia - Sesion de " + user2[0]);

        //Clase ImageIcon que permite asignar una imagen a un jLabel con la ruta en: ("")
        ImageIcon fondo = new ImageIcon("src/images/fondo unexac.jpg");
        //Clase Icon para reescalar la imagen a las coordenadas de la interfaz
        Icon icono_fondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_fondo.getWidth(), jLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        //Se le asigna la imagen de fondo al jLabel_fondo
        jLabel_fondo.setIcon(icono_fondo);
        //Instruccion necesaria para aplicar los cambios
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/iconounex.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre_materia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_codigo_materia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_seccion_materia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmb_uc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmb_especialidad = new javax.swing.JComboBox<>();
        jButton_Añadir = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setText("Añadir Materia:");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        txt_nombre_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_materiaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 290, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Código:");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        txt_codigo_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigo_materiaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_codigo_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 290, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Secciónes:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));
        getContentPane().add(txt_seccion_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 290, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Unidades de crédito:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        cmb_uc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        getContentPane().add(cmb_uc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 150, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Especialidad:");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        cmb_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mecatronica", "Sistemas", "Mecanica", "Tsu Mecanica", "Industrial" }));
        getContentPane().add(cmb_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 210, 40));

        jButton_Añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregarmateria-Icon Icons from www.icon-icons.com.png"))); // NOI18N
        jButton_Añadir.setBorder(null);
        jButton_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AñadirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 530, 90, 80));

        jLabel_footer.setText("Creado por Manuel Torrealba y Stefany Villamizar");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, -1));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AñadirActionPerformed
        int validacion = 0, uc_int = 0;
        String nombre_materia, codigo_materia, seccion_materia, especialidad_string = "";
        nombre_materia = txt_nombre_materia.getText();
        codigo_materia = txt_codigo_materia.getText();
        seccion_materia = txt_seccion_materia.getText();
        especialidad_string = cmb_especialidad.getSelectedItem().toString();
        uc_int = Integer.parseInt(cmb_uc.getSelectedItem().toString());

        if (nombre_materia.equals("")) {
            txt_nombre_materia.setBackground(Color.red);
            validacion++;
        } else {
            Validador validar_nombre_materia = new Validador(nombre_materia);
            validar_nombre_materia.ValidarNombreMateria();
            if (validar_nombre_materia.verificado == true) {
                txt_nombre_materia.setBackground(new Color(5, 125, 203));
            } else {
                txt_nombre_materia.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "NO nombre");
            }
        }

        if (codigo_materia.equals("")) {
            txt_codigo_materia.setBackground(Color.red);
            validacion++;
        } else if (codigo_materia.contains(" ")) {
            txt_codigo_materia.setBackground(Color.red);
            validacion++;
        } else {
            Validador validar_codigo_materia = new Validador(codigo_materia);
            validar_codigo_materia.ValidadorCodigoMateria();
            if (validar_codigo_materia.verificado == true) {
                txt_codigo_materia.setBackground(new Color(5, 125, 203));
            } else {
                txt_codigo_materia.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "NO codigo");
            }
        }

        if (seccion_materia.equals("")) {
            txt_seccion_materia.setBackground(Color.red);
            validacion++;
        } else if (seccion_materia.contains(" ")) {
            txt_seccion_materia.setBackground(Color.red);
            validacion++;
        } else {
            Validador validar_seccion_materia = new Validador(seccion_materia);
            validar_seccion_materia.ValidadorSeccionMateria();
            if (validar_seccion_materia.verificado == true) {
                txt_seccion_materia.setBackground(new Color(5, 125, 203));
            } else {
                txt_seccion_materia.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "NO seccion");
            }
        }

        if (validacion == 0 && actualizar == 1) {
            try {
                Connection cn2 = Conexion.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        "UPDATE materias set asignatura=?, unidades_credito=?, secciones=?, especialidad=? WHERE codigo = '" + codigo_materia + "'");

                pst2.setString(1, nombre_materia);
                pst2.setInt(2, uc_int);
                pst2.setString(3, seccion_materia);
                pst2.setString(4, especialidad_string);

                pst2.executeUpdate();
                cn2.close();

                Limpiar();
                Verificado();

                JOptionPane.showMessageDialog(null, "Modificación de materia exitosa.");
                this.dispose(); //Sirve para liberar recursos cerrando la pestaña de vista
                GestionarMaterias gestion_materias = new GestionarMaterias();
                gestion_materias.setVisible(true);
            } catch (SQLException e) {
                System.err.println("Ha ocurrido un error al actualizar la materia " + e);
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error al validar el código de la materia");
            }
        }

        if (actualizar == 0) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "SELECT codigo FROM materias WHERE codigo = '" + codigo_materia + "'");
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    txt_codigo_materia.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "El código de la asignatura ya se encuentra registrado en el sistema");
                    cn.close();
                } else {
                    cn.close();

                    if (validacion == 0) {
                        Connection cn2 = Conexion.conectar();
                        PreparedStatement pst2 = cn2.prepareStatement(
                                "INSERT into materias values (?,?,?,?,?)");

                        pst2.setString(1, codigo_materia);
                        pst2.setString(2, nombre_materia);
                        pst2.setInt(3, uc_int);
                        pst2.setString(4, seccion_materia);
                        pst2.setString(5, especialidad_string);

                        pst2.executeUpdate();
                        cn2.close();

                        Limpiar();
                        Verificado();

                        JOptionPane.showMessageDialog(null, "Registro de nueva materia exitosa.");
                        this.dispose(); //Sirve para liberar recursos cerrando la pestaña de vista
                        GestionarMaterias gestion_materias = new GestionarMaterias();
                        gestion_materias.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos");
                    }

                }
            } catch (SQLException e) {
                System.err.println("Ha ocurrido un error al validar el código de la materia " + e);
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error al validar el código de la materia");
            }
        }
    }//GEN-LAST:event_jButton_AñadirActionPerformed

    private void txt_codigo_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigo_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo_materiaActionPerformed

    private void txt_nombre_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_materiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarMateriasAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarMateriasAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarMateriasAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarMateriasAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarMateriasAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_especialidad;
    private javax.swing.JComboBox<String> cmb_uc;
    private javax.swing.JButton jButton_Añadir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JTextField txt_codigo_materia;
    private javax.swing.JTextField txt_nombre_materia;
    private javax.swing.JTextField txt_seccion_materia;
    // End of variables declaration//GEN-END:variables

    public void ActualizarDatosMaterias(String nombre_materia, String codigo_materia, String seccion_materia, String especialidad_materia, String uc_materia) {
        setTitle("Modificar materia - Sesion de " + user2[0]);
        txt_nombre_materia.setText(nombre_materia);
        txt_codigo_materia.setText(codigo_materia);
        txt_codigo_materia.setEditable(false);
        txt_seccion_materia.setText(seccion_materia);
        cmb_especialidad.setSelectedItem(especialidad_materia);
        cmb_uc.setSelectedItem(uc_materia);
        jLabel_Titulo.setText("Modificar Materia:");
        actualizar = 1;
        ImageIcon actualizar = new ImageIcon("src/images/actualizaradministradores-Icon made by Freepik Icons from www.flaticon.com.png");
        jButton_Añadir.setIcon(actualizar);
    }

    public void Limpiar() {
        txt_nombre_materia.setText("");
        txt_codigo_materia.setText("");
        txt_seccion_materia.setText("");
        cmb_especialidad.setSelectedIndex(0);
        cmb_uc.setSelectedIndex(0);
    }

    public void Verificado() {
        txt_nombre_materia.setBackground(Color.GREEN);
        txt_codigo_materia.setBackground(Color.GREEN);
        txt_seccion_materia.setBackground(Color.GREEN);
    }

}
